### ISSUE TITLE
Can't see this in all services :/

### ISSUE THREAD

**Issue by RobertMrowiec** [hyubs/franz-ryver#1]
And on the left site too, I copy Your folder to recipes in Franz folder on Mac

**Comment by hubertursua** [comment]
Hi @black09bb,

This is not yet officially ported in Franz 5 hence it won't appear in All services. Already filed a request. Until then, you have to use it in dev mode.

Check the [docs](https://github.com/meetfranz/plugins/blob/master/docs/integration.md#user-content-installation) on how to install the plugin.

For MacOS, you have to put it inside the `recipes/dev` directory. Create the `dev` directory if it does not exist. After, you should see in Franz a Development option beside the Most Popular and All services.
